services:
  server:
    build:
      context: .
      target: runner
      secrets:
        - env_prod
        - env_local
    ports:
      - "5173:8080"
    env_file:
      - path: .env.production
        required: true
      - path: .env.production.local
        required: false

secrets:
  env_prod:
    file: .env.production
  env_local:
    file: .env.production.local